project_name: kube-request
before:
  hooks:
    - go mod tidy
    - go test ./...
builds:
  - id: default
    main: ./main.go
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
changelog:
  sort: desc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
release:
  github:
    owner: ArthurMaverick