name: Release

on:
  push:
    branches:
      - main 

  workflow_dispatch:

jobs:
  tag-and-release:
    name: Tag and Release
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          install-only: true

      - name: Install GoReleaser
        id: tag_version
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          DEFAULT_BUMP: patch 
          WITH_V: true 

      - name: Executar GoReleaser
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: goreleaser release --clean

      - name: Atualizar Release Drafter
        uses: release-drafter/release-drafter@v6
        with:
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}